import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import PageContainer from "./_components/PageContainer";

const rubik = Rubik({ subsets: ["latin"], variable: "--font-rubik" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} font-rubik bg-orange-200 dark:bg-stone-800 dark:text-slate-300 h-screen box-border`}
      >
        <Navbar />
        <main className="p-3">
          <PageContainer>{children}</PageContainer>
        </main>
      </body>
    </html>
  );
}
